language: csharp
sudo: required
dist: trusty

matrix:
  include:
  - os: linux
    dist: trusty # Ubuntu 14.04
    sudo: required
  - os: osx
    osx_image: xcode8.3 # macOS 10.12

env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
  matrix:
    - CLI_VERSION=2.0.0
    - CLI_VERSION=2.0.3

addons:
  apt:
    packages:
    - gettext
    - libcurl4-openssl-dev
    - libicu-dev
    - libssl-dev
    - libunwind8
    - zlib1g

mono:
  - 5.4.1

# Make sure build dependencies are installed.
before_install:  
  - if test "$TRAVIS_OS_NAME" == "osx"; then ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi

install:
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"
  - travis_retry curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 2.0 --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"

# Run the build script
before_script:
  - chmod a+x ./build.sh
script:
  - ./build.sh --verbosity diagnostic
