version: 1.0.{build}
image: Visual Studio 2017
environment:
  matrix:
    - CLI_VERSION: 2.0.0
    - CLI_VERSION: 2.0.3
    - CLI_VERSION: Latest
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build_script:
  - ps: ./build.ps1 verbosity=diagnostic
test: off
artifacts:
  - path: artifacts/packages/*.nupkg
